#!/bin/sh

##
# General options
##

##
# Environmental variables
##

# Default programs
export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="brave-bin"

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

# Xorg
export XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"
export XAUTHORITY="$XDG_CONFIG_HOME/X11/xauthority"

# Other
# export ALSA_CONFIG_PATH="$XDG_CONFIG_HOME/alsa/asoundrc"
export GNUPGHOME="$XDG_CONFIG_HOME/gnupg"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export HISTFILE="$XDG_CONFIG_HOME/shell/history"
export HISTFILESIZE=999999
export HISTSIZE=100000
export LESSHSTFILE="-"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"

# Run shell configuration
source "$XDG_CONFIG_HOME/shell/rc"

# open the window manager on login
if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
	  exec startx
fi
