#!/bin/sh

# add .local/bin to path
export PATH="$PATH:~/.local/bin"

# aliases
### replacement aliases
alias "abook"="abook --datafile \"$XDG_DATA_HOME/abook/addressbook\""
alias "grep"="grep --color"
alias "ls"="ls --color=auto"
alias "mbsync"="mbsync -c \"$XDG_CONFIG_HOME/isync/mbsyncrc\""
alias "monero-wallet-cli"="monero-wallet-cli --log-file \"$XDG_DATA_HOME/monero/monero-wallet-cli.log\""
alias "orphanage"="pacman -Qtdq | sudo pacman -Rns -"
alias "startx"="startx $XINITRC"

# prompt
export PS1="\[\e[32m\][\[\e[m\]\[\e[1;32m\]\u\[\e[m\]\[\e[1;32m\]@\[\e[m\]\[\e[1;32m\]\h\[\e[m\] \[\e[1m\]\w\[\e[0;32m\]]\[\e[m\] "
