#!/bin/sh

sysmodmap=/etc/X11/xinit/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
usermodmap=$XDG_CONFIG_HOME/X11/xmodmap
userresources=$XDG_CONFIG_HOME/X11/xresources
wallpaper=$XDG_DATA_HOME/wallpaper

if [ -f /usr/bin/prime-offload ]; then
	prime-offload
fi

if [ -f $sysmodmap ]; then
	xmodmap $sysmodmap
fi

if [ -f $sysresources ]; then
	xrdb -merge $sysresources
fi

if [ -f "$usermodmap" ]; then
	xmodmap "$usermodmap"
fi

if [ -f "$userresources" ]; then
	xrdb -merge "$userresources"
fi

if [ -f "$wallpaper" ]; then
	xwallpaper --center $wallpaper
fi

if [ -d /etc/X11/xinit/xinitrc.d ]; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

picom & # Start picom
dwmblocks & # Start status bar
exec dwm; # Launch dwm

if [ -f /usr/bin/prime-switch ]; then
	sudo prime-switch
fi
