#!/bin/sh

modmap=$XDG_CONFIG_HOME/X11/xmodmap
resources=$XDG_CONFIG_HOME/X11/xresources
wallpaper=$XDG_DATA_HOME/wallpaper

# Set background
xwallpaper --center $wallpaper &

# Load Xresources
xrdb $resources

# Load Xmodmap
xmodmap $modmap

# Start picom
picom &

# Start status bar
slstatus &

# Start dunst
dunst &

# Start redshift
redshift -l $(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" | awk 'OFS=":" {print $3,$5}' | tr -d ',}') -t 6500K:5000K &

# Execute dwm
exec dbus-launch dwm
