#!/bin/sh

sysmodmap=/etc/X11/xinit/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
usermodmap=$XDG_CONFIG_HOME/X11/xmodmap
userresources=$XDG_CONFIG_HOME/X11/xresources

if [ -f $sysmodmap ]; then
	xmodmap $sysmodmap # Apply user Xmodmap
fi

if [ -f $sysresources ]; then
	xrdb -merge $sysresources # Merge system Xresources
fi

if [ -f "$usermodmap" ]; then
	xmodmap $usermodmap # Apply user Xmodmap
fi

if [ -f "$userresources" ]; then
	xrdb -merge $userresources # Merge user Xresources
fi

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

exec awesome; # Start awesome
